ALTER TABLE appliance_assignment ADD COLUMN last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE appliance_assignment ADD COLUMN updated_by VARCHAR(15);
ALTER TABLE appliance_assignment ADD COLUMN version VARCHAR(15) DEFAULT NULL;
